# Generated by Django 3.0.4 on 2021-02-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_orderline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('uk', 'United Kingdom'), ('us', 'United States of America'), ('sa', 'South Africa')], max_length=3),
        ),
    ]
